package eu.comvantage.domainconfiguration;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-05-15T18:30:37.317+02:00
 * Generated source version: 2.6.1
 * 
 */
@WebServiceClient(name = "DomainConfigurationServiceImplService", 
                  wsdlLocation = "http://localhost:8080/DomainConfiguration/services/DomainConfigurationServiceImplPort?wsdl",
                  targetNamespace = "http://domainconfiguration.comvantage.eu/") 
public class DomainConfigurationServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://domainconfiguration.comvantage.eu/", "DomainConfigurationServiceImplService");
    public final static QName DomainConfigurationServiceImplPort = new QName("http://domainconfiguration.comvantage.eu/", "DomainConfigurationServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/DomainConfiguration/services/DomainConfigurationServiceImplPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DomainConfigurationServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/DomainConfiguration/services/DomainConfigurationServiceImplPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DomainConfigurationServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DomainConfigurationServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DomainConfigurationServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns DomainConfigurationServiceImpl
     */
    @WebEndpoint(name = "DomainConfigurationServiceImplPort")
    public DomainConfigurationServiceImpl getDomainConfigurationServiceImplPort() {
        return super.getPort(DomainConfigurationServiceImplPort, DomainConfigurationServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DomainConfigurationServiceImpl
     */
    @WebEndpoint(name = "DomainConfigurationServiceImplPort")
    public DomainConfigurationServiceImpl getDomainConfigurationServiceImplPort(WebServiceFeature... features) {
        return super.getPort(DomainConfigurationServiceImplPort, DomainConfigurationServiceImpl.class, features);
    }

}
