package eu.comvantage.domainconfiguration;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-05-15T18:30:37.308+02:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://domainconfiguration.comvantage.eu/", name = "DomainConfigurationServiceImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface DomainConfigurationServiceImpl {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllDomainSources", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.GetAllDomainSources")
    @WebMethod
    @ResponseWrapper(localName = "getAllDomainSourcesResponse", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.GetAllDomainSourcesResponse")
    public java.util.List<eu.comvantage.domainconfiguration.DomainSourceDetail> getAllDomainSources();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDomainSourcesByType", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.GetDomainSourcesByType")
    @WebMethod
    @ResponseWrapper(localName = "getDomainSourcesByTypeResponse", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.GetDomainSourcesByTypeResponse")
    public java.util.List<eu.comvantage.domainconfiguration.DomainSourceDetail> getDomainSourcesByType(
        @WebParam(name = "type", targetNamespace = "")
        java.lang.String type
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllDomainSPARULTemplates", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.GetAllDomainSPARULTemplates")
    @WebMethod
    @ResponseWrapper(localName = "getAllDomainSPARULTemplatesResponse", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.GetAllDomainSPARULTemplatesResponse")
    public java.util.List<eu.comvantage.domainconfiguration.DomainSPARULTemplate> getAllDomainSPARULTemplates();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDomainSPARULTemplateById", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.GetDomainSPARULTemplateById")
    @WebMethod
    @ResponseWrapper(localName = "getDomainSPARULTemplateByIdResponse", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.GetDomainSPARULTemplateByIdResponse")
    public eu.comvantage.domainconfiguration.DomainSPARULTemplate getDomainSPARULTemplateById(
        @WebParam(name = "templateId", targetNamespace = "")
        java.lang.Long templateId,
        @WebParam(name = "clientId", targetNamespace = "")
        java.lang.Long clientId
    );

    @RequestWrapper(localName = "deleteDomainSystemParameter", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.DeleteDomainSystemParameter")
    @WebMethod
    @ResponseWrapper(localName = "deleteDomainSystemParameterResponse", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.DeleteDomainSystemParameterResponse")
    public void deleteDomainSystemParameter(
        @WebParam(name = "param", targetNamespace = "")
        eu.comvantage.domainconfiguration.DomainSystemParameter param
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "wstestSingle", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.WstestSingle")
    @WebMethod
    @ResponseWrapper(localName = "wstestSingleResponse", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.WstestSingleResponse")
    public java.lang.String wstestSingle(
        @WebParam(name = "testparam", targetNamespace = "")
        java.lang.String testparam
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllDomainRoles", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.GetAllDomainRoles")
    @WebMethod
    @ResponseWrapper(localName = "getAllDomainRolesResponse", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.GetAllDomainRolesResponse")
    public java.util.List<eu.comvantage.domainconfiguration.DomainRole> getAllDomainRoles();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDomainSystemParametersByKey", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.GetDomainSystemParametersByKey")
    @WebMethod
    @ResponseWrapper(localName = "getDomainSystemParametersByKeyResponse", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.GetDomainSystemParametersByKeyResponse")
    public java.util.List<eu.comvantage.domainconfiguration.DomainSystemParameter> getDomainSystemParametersByKey(
        @WebParam(name = "key", targetNamespace = "")
        java.lang.String key
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllDomainSystemParameters", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.GetAllDomainSystemParameters")
    @WebMethod
    @ResponseWrapper(localName = "getAllDomainSystemParametersResponse", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.GetAllDomainSystemParametersResponse")
    public java.util.List<eu.comvantage.domainconfiguration.DomainSystemParameter> getAllDomainSystemParameters();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDomainSourcesById", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.GetDomainSourcesById")
    @WebMethod
    @ResponseWrapper(localName = "getDomainSourcesByIdResponse", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.GetDomainSourcesByIdResponse")
    public eu.comvantage.domainconfiguration.DomainSourceDetail getDomainSourcesById(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.Long id
    );

    @RequestWrapper(localName = "clearDomainConfiguration", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.ClearDomainConfiguration")
    @WebMethod
    @ResponseWrapper(localName = "clearDomainConfigurationResponse", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.ClearDomainConfigurationResponse")
    public void clearDomainConfiguration();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getVersion", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.GetVersion")
    @WebMethod
    @ResponseWrapper(localName = "getVersionResponse", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.GetVersionResponse")
    public java.lang.String getVersion();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "hasUseRightsForSPARULTemplate", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.HasUseRightsForSPARULTemplate")
    @WebMethod
    @ResponseWrapper(localName = "hasUseRightsForSPARULTemplateResponse", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.HasUseRightsForSPARULTemplateResponse")
    public boolean hasUseRightsForSPARULTemplate(
        @WebParam(name = "userRole", targetNamespace = "")
        java.lang.String userRole,
        @WebParam(name = "templateId", targetNamespace = "")
        java.lang.Long templateId,
        @WebParam(name = "clientId", targetNamespace = "")
        java.lang.Long clientId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "wstestComplex", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.WstestComplex")
    @WebMethod
    @ResponseWrapper(localName = "wstestComplexResponse", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.WstestComplexResponse")
    public java.util.List<java.lang.String> wstestComplex();

    @RequestWrapper(localName = "addDomainSystemParameter", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.AddDomainSystemParameter")
    @WebMethod
    @ResponseWrapper(localName = "addDomainSystemParameterResponse", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.AddDomainSystemParameterResponse")
    public void addDomainSystemParameter(
        @WebParam(name = "param", targetNamespace = "")
        eu.comvantage.domainconfiguration.DomainSystemParameter param
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllDomainViewActions", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.GetAllDomainViewActions")
    @WebMethod
    @ResponseWrapper(localName = "getAllDomainViewActionsResponse", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.GetAllDomainViewActionsResponse")
    public java.util.List<eu.comvantage.domainconfiguration.DomainViewAction> getAllDomainViewActions();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "wstestSuperComplex", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.WstestSuperComplex")
    @WebMethod
    @ResponseWrapper(localName = "wstestSuperComplexResponse", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.WstestSuperComplexResponse")
    public java.util.List<eu.comvantage.domainconfiguration.DomainSourceDetail> wstestSuperComplex();

    @RequestWrapper(localName = "addDomainSource", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.AddDomainSource")
    @WebMethod
    @ResponseWrapper(localName = "addDomainSourceResponse", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.AddDomainSourceResponse")
    public void addDomainSource(
        @WebParam(name = "source", targetNamespace = "")
        eu.comvantage.domainconfiguration.DomainSourceDetail source
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDomainSourcesByName", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.GetDomainSourcesByName")
    @WebMethod
    @ResponseWrapper(localName = "getDomainSourcesByNameResponse", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.GetDomainSourcesByNameResponse")
    public eu.comvantage.domainconfiguration.DomainSourceDetail getDomainSourcesByName(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDomainSourcesByContent", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.GetDomainSourcesByContent")
    @WebMethod
    @ResponseWrapper(localName = "getDomainSourcesByContentResponse", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.GetDomainSourcesByContentResponse")
    public java.util.List<eu.comvantage.domainconfiguration.DomainSourceDetail> getDomainSourcesByContent(
        @WebParam(name = "contents", targetNamespace = "")
        java.util.List<java.lang.String> contents
    );

    @RequestWrapper(localName = "deleteDomainSource", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.DeleteDomainSource")
    @WebMethod
    @ResponseWrapper(localName = "deleteDomainSourceResponse", targetNamespace = "http://domainconfiguration.comvantage.eu/", className = "eu.comvantage.domainconfiguration.DeleteDomainSourceResponse")
    public void deleteDomainSource(
        @WebParam(name = "source", targetNamespace = "")
        eu.comvantage.domainconfiguration.DomainSourceDetail source
    );
}
