
package eu.comvantage.domainconfiguration;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-05-15T18:30:37.231+02:00
 * Generated source version: 2.6.1
 * 
 */
public final class DomainConfigurationServiceImpl_DomainConfigurationServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://domainconfiguration.comvantage.eu/", "DomainConfigurationServiceImplService");

    private DomainConfigurationServiceImpl_DomainConfigurationServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = DomainConfigurationServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        DomainConfigurationServiceImplService ss = new DomainConfigurationServiceImplService(wsdlURL, SERVICE_NAME);
        DomainConfigurationServiceImpl port = ss.getDomainConfigurationServiceImplPort();  
        
        {
        System.out.println("Invoking getAllDomainSources...");
        java.util.List<eu.comvantage.domainconfiguration.DomainSourceDetail> _getAllDomainSources__return = port.getAllDomainSources();
        System.out.println("getAllDomainSources.result=" + _getAllDomainSources__return);


        }
        {
        System.out.println("Invoking getDomainSourcesByType...");
        java.lang.String _getDomainSourcesByType_type = "_getDomainSourcesByType_type1969794573";
        java.util.List<eu.comvantage.domainconfiguration.DomainSourceDetail> _getDomainSourcesByType__return = port.getDomainSourcesByType(_getDomainSourcesByType_type);
        System.out.println("getDomainSourcesByType.result=" + _getDomainSourcesByType__return);


        }
        {
        System.out.println("Invoking getAllDomainSPARULTemplates...");
        java.util.List<eu.comvantage.domainconfiguration.DomainSPARULTemplate> _getAllDomainSPARULTemplates__return = port.getAllDomainSPARULTemplates();
        System.out.println("getAllDomainSPARULTemplates.result=" + _getAllDomainSPARULTemplates__return);


        }
        {
        System.out.println("Invoking getDomainSPARULTemplateById...");
        java.lang.Long _getDomainSPARULTemplateById_templateId = Long.valueOf(-5736761665019868808l);
        java.lang.Long _getDomainSPARULTemplateById_clientId = Long.valueOf(-8284580534136560309l);
        eu.comvantage.domainconfiguration.DomainSPARULTemplate _getDomainSPARULTemplateById__return = port.getDomainSPARULTemplateById(_getDomainSPARULTemplateById_templateId, _getDomainSPARULTemplateById_clientId);
        System.out.println("getDomainSPARULTemplateById.result=" + _getDomainSPARULTemplateById__return);


        }
        {
        System.out.println("Invoking deleteDomainSystemParameter...");
        eu.comvantage.domainconfiguration.DomainSystemParameter _deleteDomainSystemParameter_param = new eu.comvantage.domainconfiguration.DomainSystemParameter();
        _deleteDomainSystemParameter_param.setId(-376875368);
        _deleteDomainSystemParameter_param.setKey("Key1317902632");
        _deleteDomainSystemParameter_param.setValue("Value-774535179");
        port.deleteDomainSystemParameter(_deleteDomainSystemParameter_param);


        }
        {
        System.out.println("Invoking wstestSingle...");
        java.lang.String _wstestSingle_testparam = "_wstestSingle_testparam1599132697";
        java.lang.String _wstestSingle__return = port.wstestSingle(_wstestSingle_testparam);
        System.out.println("wstestSingle.result=" + _wstestSingle__return);


        }
        {
        System.out.println("Invoking getAllDomainRoles...");
        java.util.List<eu.comvantage.domainconfiguration.DomainRole> _getAllDomainRoles__return = port.getAllDomainRoles();
        System.out.println("getAllDomainRoles.result=" + _getAllDomainRoles__return);


        }
        {
        System.out.println("Invoking getDomainSystemParametersByKey...");
        java.lang.String _getDomainSystemParametersByKey_key = "_getDomainSystemParametersByKey_key1993077633";
        java.util.List<eu.comvantage.domainconfiguration.DomainSystemParameter> _getDomainSystemParametersByKey__return = port.getDomainSystemParametersByKey(_getDomainSystemParametersByKey_key);
        System.out.println("getDomainSystemParametersByKey.result=" + _getDomainSystemParametersByKey__return);


        }
        {
        System.out.println("Invoking getAllDomainSystemParameters...");
        java.util.List<eu.comvantage.domainconfiguration.DomainSystemParameter> _getAllDomainSystemParameters__return = port.getAllDomainSystemParameters();
        System.out.println("getAllDomainSystemParameters.result=" + _getAllDomainSystemParameters__return);


        }
        {
        System.out.println("Invoking getDomainSourcesById...");
        java.lang.Long _getDomainSourcesById_id = Long.valueOf(-6532830365828541680l);
        eu.comvantage.domainconfiguration.DomainSourceDetail _getDomainSourcesById__return = port.getDomainSourcesById(_getDomainSourcesById_id);
        System.out.println("getDomainSourcesById.result=" + _getDomainSourcesById__return);


        }
        {
        System.out.println("Invoking clearDomainConfiguration...");
        port.clearDomainConfiguration();


        }
        {
        System.out.println("Invoking getVersion...");
        java.lang.String _getVersion__return = port.getVersion();
        System.out.println("getVersion.result=" + _getVersion__return);


        }
        {
        System.out.println("Invoking hasUseRightsForSPARULTemplate...");
        java.lang.String _hasUseRightsForSPARULTemplate_userRole = "_hasUseRightsForSPARULTemplate_userRole105816772";
        java.lang.Long _hasUseRightsForSPARULTemplate_templateId = Long.valueOf(-5421670406728379214l);
        java.lang.Long _hasUseRightsForSPARULTemplate_clientId = Long.valueOf(-4376106183711382097l);
        boolean _hasUseRightsForSPARULTemplate__return = port.hasUseRightsForSPARULTemplate(_hasUseRightsForSPARULTemplate_userRole, _hasUseRightsForSPARULTemplate_templateId, _hasUseRightsForSPARULTemplate_clientId);
        System.out.println("hasUseRightsForSPARULTemplate.result=" + _hasUseRightsForSPARULTemplate__return);


        }
        {
        System.out.println("Invoking wstestComplex...");
        java.util.List<java.lang.String> _wstestComplex__return = port.wstestComplex();
        System.out.println("wstestComplex.result=" + _wstestComplex__return);


        }
        {
        System.out.println("Invoking addDomainSystemParameter...");
        eu.comvantage.domainconfiguration.DomainSystemParameter _addDomainSystemParameter_param = new eu.comvantage.domainconfiguration.DomainSystemParameter();
        _addDomainSystemParameter_param.setId(536858419);
        _addDomainSystemParameter_param.setKey("Key-264337495");
        _addDomainSystemParameter_param.setValue("Value612697850");
        port.addDomainSystemParameter(_addDomainSystemParameter_param);


        }
        {
        System.out.println("Invoking getAllDomainViewActions...");
        java.util.List<eu.comvantage.domainconfiguration.DomainViewAction> _getAllDomainViewActions__return = port.getAllDomainViewActions();
        System.out.println("getAllDomainViewActions.result=" + _getAllDomainViewActions__return);


        }
        {
        System.out.println("Invoking wstestSuperComplex...");
        java.util.List<eu.comvantage.domainconfiguration.DomainSourceDetail> _wstestSuperComplex__return = port.wstestSuperComplex();
        System.out.println("wstestSuperComplex.result=" + _wstestSuperComplex__return);


        }
        {
        System.out.println("Invoking addDomainSource...");
        eu.comvantage.domainconfiguration.DomainSourceDetail _addDomainSource_source = new eu.comvantage.domainconfiguration.DomainSourceDetail();
        java.util.List<java.lang.String> _addDomainSource_sourceContent = new java.util.ArrayList<java.lang.String>();
        java.lang.String _addDomainSource_sourceContentVal1 = "_addDomainSource_sourceContentVal2012895971";
        _addDomainSource_sourceContent.add(_addDomainSource_sourceContentVal1);
        _addDomainSource_source.getContent().addAll(_addDomainSource_sourceContent);
        _addDomainSource_source.setId(Long.valueOf(8842257110083503134l));
        _addDomainSource_source.setName("Name-974155822");
        _addDomainSource_source.setPassword("Password-1857209397");
        _addDomainSource_source.setQueryEndpointURL("QueryEndpointURL1981727341");
        _addDomainSource_source.setType("Type1421968005");
        _addDomainSource_source.setUpdateEndpointURL("UpdateEndpointURL82267058");
        _addDomainSource_source.setUsername("Username-928733385");
        port.addDomainSource(_addDomainSource_source);


        }
        {
        System.out.println("Invoking getDomainSourcesByName...");
        java.lang.String _getDomainSourcesByName_name = "_getDomainSourcesByName_name133379568";
        eu.comvantage.domainconfiguration.DomainSourceDetail _getDomainSourcesByName__return = port.getDomainSourcesByName(_getDomainSourcesByName_name);
        System.out.println("getDomainSourcesByName.result=" + _getDomainSourcesByName__return);


        }
        {
        System.out.println("Invoking getDomainSourcesByContent...");
        java.util.List<java.lang.String> _getDomainSourcesByContent_contents = new java.util.ArrayList<java.lang.String>();
        java.lang.String _getDomainSourcesByContent_contentsVal1 = "_getDomainSourcesByContent_contentsVal-933223024";
        _getDomainSourcesByContent_contents.add(_getDomainSourcesByContent_contentsVal1);
        java.util.List<eu.comvantage.domainconfiguration.DomainSourceDetail> _getDomainSourcesByContent__return = port.getDomainSourcesByContent(_getDomainSourcesByContent_contents);
        System.out.println("getDomainSourcesByContent.result=" + _getDomainSourcesByContent__return);


        }
        {
        System.out.println("Invoking deleteDomainSource...");
        eu.comvantage.domainconfiguration.DomainSourceDetail _deleteDomainSource_source = new eu.comvantage.domainconfiguration.DomainSourceDetail();
        java.util.List<java.lang.String> _deleteDomainSource_sourceContent = new java.util.ArrayList<java.lang.String>();
        java.lang.String _deleteDomainSource_sourceContentVal1 = "_deleteDomainSource_sourceContentVal-1364820773";
        _deleteDomainSource_sourceContent.add(_deleteDomainSource_sourceContentVal1);
        _deleteDomainSource_source.getContent().addAll(_deleteDomainSource_sourceContent);
        _deleteDomainSource_source.setId(Long.valueOf(2728450930263366607l));
        _deleteDomainSource_source.setName("Name1796240412");
        _deleteDomainSource_source.setPassword("Password-1686214823");
        _deleteDomainSource_source.setQueryEndpointURL("QueryEndpointURL-2143168047");
        _deleteDomainSource_source.setType("Type-490353827");
        _deleteDomainSource_source.setUpdateEndpointURL("UpdateEndpointURL479382861");
        _deleteDomainSource_source.setUsername("Username-2058871724");
        port.deleteDomainSource(_deleteDomainSource_source);


        }

        System.exit(0);
    }

}
