
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package eu.comvantage.domainconfiguration;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-05-15T18:30:37.285+02:00
 * Generated source version: 2.6.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "DomainConfigurationServiceImplService",
                      portName = "DomainConfigurationServiceImplPort",
                      targetNamespace = "http://domainconfiguration.comvantage.eu/",
                      wsdlLocation = "http://localhost:8080/DomainConfiguration/services/DomainConfigurationServiceImplPort?wsdl",
                      endpointInterface = "eu.comvantage.domainconfiguration.DomainConfigurationServiceImpl")
                      
public class DomainConfigurationServiceImplImpl implements DomainConfigurationServiceImpl {

    private static final Logger LOG = Logger.getLogger(DomainConfigurationServiceImplImpl.class.getName());

    /* (non-Javadoc)
     * @see eu.comvantage.domainconfiguration.DomainConfigurationServiceImpl#getAllDomainSources(*
     */
    public java.util.List<eu.comvantage.domainconfiguration.DomainSourceDetail> getAllDomainSources() { 
        LOG.info("Executing operation getAllDomainSources");
        try {
            java.util.List<eu.comvantage.domainconfiguration.DomainSourceDetail> _return = new java.util.ArrayList<eu.comvantage.domainconfiguration.DomainSourceDetail>();
            eu.comvantage.domainconfiguration.DomainSourceDetail _returnVal1 = new eu.comvantage.domainconfiguration.DomainSourceDetail();
            java.util.List<java.lang.String> _returnVal1Content = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnVal1ContentVal1 = "_returnVal1ContentVal1823340368";
            _returnVal1Content.add(_returnVal1ContentVal1);
            _returnVal1.getContent().addAll(_returnVal1Content);
            _returnVal1.setId(Long.valueOf(-2388067315798607113l));
            _returnVal1.setName("Name516302501");
            _returnVal1.setPassword("Password1671612868");
            _returnVal1.setQueryEndpointURL("QueryEndpointURL-1299197691");
            _returnVal1.setType("Type-1404697025");
            _returnVal1.setUpdateEndpointURL("UpdateEndpointURL1436282028");
            _returnVal1.setUsername("Username552569349");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.comvantage.domainconfiguration.DomainConfigurationServiceImpl#getDomainSourcesByType(java.lang.String  type )*
     */
    public java.util.List<eu.comvantage.domainconfiguration.DomainSourceDetail> getDomainSourcesByType(java.lang.String type) { 
        LOG.info("Executing operation getDomainSourcesByType");
        System.out.println(type);
        try {
            java.util.List<eu.comvantage.domainconfiguration.DomainSourceDetail> _return = new java.util.ArrayList<eu.comvantage.domainconfiguration.DomainSourceDetail>();
            eu.comvantage.domainconfiguration.DomainSourceDetail _returnVal1 = new eu.comvantage.domainconfiguration.DomainSourceDetail();
            java.util.List<java.lang.String> _returnVal1Content = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnVal1ContentVal1 = "_returnVal1ContentVal-930755759";
            _returnVal1Content.add(_returnVal1ContentVal1);
            _returnVal1.getContent().addAll(_returnVal1Content);
            _returnVal1.setId(Long.valueOf(-3443650073513632928l));
            _returnVal1.setName("Name-1137250389");
            _returnVal1.setPassword("Password2030744282");
            _returnVal1.setQueryEndpointURL("QueryEndpointURL-724286860");
            _returnVal1.setType("Type644001446");
            _returnVal1.setUpdateEndpointURL("UpdateEndpointURL-923044653");
            _returnVal1.setUsername("Username618597879");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.comvantage.domainconfiguration.DomainConfigurationServiceImpl#getAllDomainSPARULTemplates(*
     */
    public java.util.List<eu.comvantage.domainconfiguration.DomainSPARULTemplate> getAllDomainSPARULTemplates() { 
        LOG.info("Executing operation getAllDomainSPARULTemplates");
        try {
            java.util.List<eu.comvantage.domainconfiguration.DomainSPARULTemplate> _return = new java.util.ArrayList<eu.comvantage.domainconfiguration.DomainSPARULTemplate>();
            eu.comvantage.domainconfiguration.DomainSPARULTemplate _returnVal1 = new eu.comvantage.domainconfiguration.DomainSPARULTemplate();
            _returnVal1.setClient(Long.valueOf(-2881059613595440409l));
            _returnVal1.setEnabled(true);
            _returnVal1.setId(Long.valueOf(-1974216545267115105l));
            _returnVal1.setName("Name-355148836");
            java.util.List<eu.comvantage.domainconfiguration.DomainRole> _returnVal1Roles = new java.util.ArrayList<eu.comvantage.domainconfiguration.DomainRole>();
            eu.comvantage.domainconfiguration.DomainRole _returnVal1RolesVal1 = new eu.comvantage.domainconfiguration.DomainRole();
            _returnVal1RolesVal1.setClient(Long.valueOf(7323757935663609040l));
            _returnVal1RolesVal1.setId(Long.valueOf(-4424517480430654293l));
            _returnVal1RolesVal1.setName("Name1466958412");
            _returnVal1Roles.add(_returnVal1RolesVal1);
            _returnVal1.getRoles().addAll(_returnVal1Roles);
            _returnVal1.setSource("Source-31781926");
            _returnVal1.setStatement("Statement-100555882");
            java.util.List<eu.comvantage.domainconfiguration.DomainViewAction> _returnVal1Viewactions = new java.util.ArrayList<eu.comvantage.domainconfiguration.DomainViewAction>();
            eu.comvantage.domainconfiguration.DomainViewAction _returnVal1ViewactionsVal1 = new eu.comvantage.domainconfiguration.DomainViewAction();
            _returnVal1ViewactionsVal1.setClient(Long.valueOf(-3456111157192294723l));
            _returnVal1ViewactionsVal1.setId(Long.valueOf(2554188320655143766l));
            _returnVal1ViewactionsVal1.setName("Name-826140493");
            _returnVal1ViewactionsVal1.setStatement("Statement2005854284");
            _returnVal1Viewactions.add(_returnVal1ViewactionsVal1);
            _returnVal1.getViewactions().addAll(_returnVal1Viewactions);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.comvantage.domainconfiguration.DomainConfigurationServiceImpl#getDomainSPARULTemplateById(java.lang.Long  templateId ,)java.lang.Long  clientId )*
     */
    public eu.comvantage.domainconfiguration.DomainSPARULTemplate getDomainSPARULTemplateById(java.lang.Long templateId,java.lang.Long clientId) { 
        LOG.info("Executing operation getDomainSPARULTemplateById");
        System.out.println(templateId);
        System.out.println(clientId);
        try {
            eu.comvantage.domainconfiguration.DomainSPARULTemplate _return = new eu.comvantage.domainconfiguration.DomainSPARULTemplate();
            _return.setClient(Long.valueOf(-7505315374884404014l));
            _return.setEnabled(false);
            _return.setId(Long.valueOf(4465949336903458463l));
            _return.setName("Name1986612009");
            java.util.List<eu.comvantage.domainconfiguration.DomainRole> _returnRoles = new java.util.ArrayList<eu.comvantage.domainconfiguration.DomainRole>();
            eu.comvantage.domainconfiguration.DomainRole _returnRolesVal1 = new eu.comvantage.domainconfiguration.DomainRole();
            _returnRolesVal1.setClient(Long.valueOf(8366498543820382156l));
            _returnRolesVal1.setId(Long.valueOf(3354281231119889138l));
            _returnRolesVal1.setName("Name960558003");
            _returnRoles.add(_returnRolesVal1);
            _return.getRoles().addAll(_returnRoles);
            _return.setSource("Source-571913290");
            _return.setStatement("Statement510540218");
            java.util.List<eu.comvantage.domainconfiguration.DomainViewAction> _returnViewactions = new java.util.ArrayList<eu.comvantage.domainconfiguration.DomainViewAction>();
            eu.comvantage.domainconfiguration.DomainViewAction _returnViewactionsVal1 = new eu.comvantage.domainconfiguration.DomainViewAction();
            _returnViewactionsVal1.setClient(Long.valueOf(1985972692600863112l));
            _returnViewactionsVal1.setId(Long.valueOf(4584282311929289740l));
            _returnViewactionsVal1.setName("Name1382509368");
            _returnViewactionsVal1.setStatement("Statement-1285312049");
            _returnViewactions.add(_returnViewactionsVal1);
            _return.getViewactions().addAll(_returnViewactions);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.comvantage.domainconfiguration.DomainConfigurationServiceImpl#deleteDomainSystemParameter(eu.comvantage.domainconfiguration.DomainSystemParameter  param )*
     */
    public void deleteDomainSystemParameter(eu.comvantage.domainconfiguration.DomainSystemParameter param) { 
        LOG.info("Executing operation deleteDomainSystemParameter");
        System.out.println(param);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.comvantage.domainconfiguration.DomainConfigurationServiceImpl#wstestSingle(java.lang.String  testparam )*
     */
    public java.lang.String wstestSingle(java.lang.String testparam) { 
        LOG.info("Executing operation wstestSingle");
        System.out.println(testparam);
        try {
            java.lang.String _return = "_return1847271287";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.comvantage.domainconfiguration.DomainConfigurationServiceImpl#getAllDomainRoles(*
     */
    public java.util.List<eu.comvantage.domainconfiguration.DomainRole> getAllDomainRoles() { 
        LOG.info("Executing operation getAllDomainRoles");
        try {
            java.util.List<eu.comvantage.domainconfiguration.DomainRole> _return = new java.util.ArrayList<eu.comvantage.domainconfiguration.DomainRole>();
            eu.comvantage.domainconfiguration.DomainRole _returnVal1 = new eu.comvantage.domainconfiguration.DomainRole();
            _returnVal1.setClient(Long.valueOf(5638663221673866252l));
            _returnVal1.setId(Long.valueOf(6970591206254317188l));
            _returnVal1.setName("Name-1155211209");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.comvantage.domainconfiguration.DomainConfigurationServiceImpl#getDomainSystemParametersByKey(java.lang.String  key )*
     */
    public java.util.List<eu.comvantage.domainconfiguration.DomainSystemParameter> getDomainSystemParametersByKey(java.lang.String key) { 
        LOG.info("Executing operation getDomainSystemParametersByKey");
        System.out.println(key);
        try {
            java.util.List<eu.comvantage.domainconfiguration.DomainSystemParameter> _return = new java.util.ArrayList<eu.comvantage.domainconfiguration.DomainSystemParameter>();
            eu.comvantage.domainconfiguration.DomainSystemParameter _returnVal1 = new eu.comvantage.domainconfiguration.DomainSystemParameter();
            _returnVal1.setId(1726104842);
            _returnVal1.setKey("Key1305486087");
            _returnVal1.setValue("Value588779176");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.comvantage.domainconfiguration.DomainConfigurationServiceImpl#getAllDomainSystemParameters(*
     */
    public java.util.List<eu.comvantage.domainconfiguration.DomainSystemParameter> getAllDomainSystemParameters() { 
        LOG.info("Executing operation getAllDomainSystemParameters");
        try {
            java.util.List<eu.comvantage.domainconfiguration.DomainSystemParameter> _return = new java.util.ArrayList<eu.comvantage.domainconfiguration.DomainSystemParameter>();
            eu.comvantage.domainconfiguration.DomainSystemParameter _returnVal1 = new eu.comvantage.domainconfiguration.DomainSystemParameter();
            _returnVal1.setId(-1945216994);
            _returnVal1.setKey("Key-1032203255");
            _returnVal1.setValue("Value-2074398685");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.comvantage.domainconfiguration.DomainConfigurationServiceImpl#getDomainSourcesById(java.lang.Long  id )*
     */
    public eu.comvantage.domainconfiguration.DomainSourceDetail getDomainSourcesById(java.lang.Long id) { 
        LOG.info("Executing operation getDomainSourcesById");
        System.out.println(id);
        try {
            eu.comvantage.domainconfiguration.DomainSourceDetail _return = new eu.comvantage.domainconfiguration.DomainSourceDetail();
            java.util.List<java.lang.String> _returnContent = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnContentVal1 = "_returnContentVal-2012274909";
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            _return.setId(Long.valueOf(6829664722569826930l));
            _return.setName("Name-308654485");
            _return.setPassword("Password-1276730192");
            _return.setQueryEndpointURL("QueryEndpointURL934353091");
            _return.setType("Type-1082151898");
            _return.setUpdateEndpointURL("UpdateEndpointURL-1242004723");
            _return.setUsername("Username416275726");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.comvantage.domainconfiguration.DomainConfigurationServiceImpl#clearDomainConfiguration(*
     */
    public void clearDomainConfiguration() { 
        LOG.info("Executing operation clearDomainConfiguration");
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.comvantage.domainconfiguration.DomainConfigurationServiceImpl#getVersion(*
     */
    public java.lang.String getVersion() { 
        LOG.info("Executing operation getVersion");
        try {
            java.lang.String _return = "_return-344296802";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.comvantage.domainconfiguration.DomainConfigurationServiceImpl#hasUseRightsForSPARULTemplate(java.lang.String  userRole ,)java.lang.Long  templateId ,)java.lang.Long  clientId )*
     */
    public boolean hasUseRightsForSPARULTemplate(java.lang.String userRole,java.lang.Long templateId,java.lang.Long clientId) { 
        LOG.info("Executing operation hasUseRightsForSPARULTemplate");
        System.out.println(userRole);
        System.out.println(templateId);
        System.out.println(clientId);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.comvantage.domainconfiguration.DomainConfigurationServiceImpl#wstestComplex(*
     */
    public java.util.List<java.lang.String> wstestComplex() { 
        LOG.info("Executing operation wstestComplex");
        try {
            java.util.List<java.lang.String> _return = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnVal1 = "_returnVal1146876256";
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.comvantage.domainconfiguration.DomainConfigurationServiceImpl#addDomainSystemParameter(eu.comvantage.domainconfiguration.DomainSystemParameter  param )*
     */
    public void addDomainSystemParameter(eu.comvantage.domainconfiguration.DomainSystemParameter param) { 
        LOG.info("Executing operation addDomainSystemParameter");
        System.out.println(param);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.comvantage.domainconfiguration.DomainConfigurationServiceImpl#getAllDomainViewActions(*
     */
    public java.util.List<eu.comvantage.domainconfiguration.DomainViewAction> getAllDomainViewActions() { 
        LOG.info("Executing operation getAllDomainViewActions");
        try {
            java.util.List<eu.comvantage.domainconfiguration.DomainViewAction> _return = new java.util.ArrayList<eu.comvantage.domainconfiguration.DomainViewAction>();
            eu.comvantage.domainconfiguration.DomainViewAction _returnVal1 = new eu.comvantage.domainconfiguration.DomainViewAction();
            _returnVal1.setClient(Long.valueOf(-307504010813152674l));
            _returnVal1.setId(Long.valueOf(8122006995576391808l));
            _returnVal1.setName("Name-862600958");
            _returnVal1.setStatement("Statement857375667");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.comvantage.domainconfiguration.DomainConfigurationServiceImpl#wstestSuperComplex(*
     */
    public java.util.List<eu.comvantage.domainconfiguration.DomainSourceDetail> wstestSuperComplex() { 
        LOG.info("Executing operation wstestSuperComplex");
        try {
            java.util.List<eu.comvantage.domainconfiguration.DomainSourceDetail> _return = new java.util.ArrayList<eu.comvantage.domainconfiguration.DomainSourceDetail>();
            eu.comvantage.domainconfiguration.DomainSourceDetail _returnVal1 = new eu.comvantage.domainconfiguration.DomainSourceDetail();
            java.util.List<java.lang.String> _returnVal1Content = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnVal1ContentVal1 = "_returnVal1ContentVal-1983551390";
            _returnVal1Content.add(_returnVal1ContentVal1);
            _returnVal1.getContent().addAll(_returnVal1Content);
            _returnVal1.setId(Long.valueOf(-914945288415647688l));
            _returnVal1.setName("Name-536022526");
            _returnVal1.setPassword("Password1000488552");
            _returnVal1.setQueryEndpointURL("QueryEndpointURL-1556122994");
            _returnVal1.setType("Type1863742017");
            _returnVal1.setUpdateEndpointURL("UpdateEndpointURL1879983260");
            _returnVal1.setUsername("Username-689045838");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.comvantage.domainconfiguration.DomainConfigurationServiceImpl#addDomainSource(eu.comvantage.domainconfiguration.DomainSourceDetail  source )*
     */
    public void addDomainSource(eu.comvantage.domainconfiguration.DomainSourceDetail source) { 
        LOG.info("Executing operation addDomainSource");
        System.out.println(source);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.comvantage.domainconfiguration.DomainConfigurationServiceImpl#getDomainSourcesByName(java.lang.String  name )*
     */
    public eu.comvantage.domainconfiguration.DomainSourceDetail getDomainSourcesByName(java.lang.String name) { 
        LOG.info("Executing operation getDomainSourcesByName");
        System.out.println(name);
        try {
            eu.comvantage.domainconfiguration.DomainSourceDetail _return = new eu.comvantage.domainconfiguration.DomainSourceDetail();
            java.util.List<java.lang.String> _returnContent = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnContentVal1 = "_returnContentVal-1290323413";
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            _return.setId(Long.valueOf(-2658514281380865487l));
            _return.setName("Name1400779417");
            _return.setPassword("Password-1723414564");
            _return.setQueryEndpointURL("QueryEndpointURL-1259891952");
            _return.setType("Type525297542");
            _return.setUpdateEndpointURL("UpdateEndpointURL1498567976");
            _return.setUsername("Username555033837");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.comvantage.domainconfiguration.DomainConfigurationServiceImpl#getDomainSourcesByContent(java.util.List<java.lang.String>  contents )*
     */
    public java.util.List<eu.comvantage.domainconfiguration.DomainSourceDetail> getDomainSourcesByContent(java.util.List<java.lang.String> contents) { 
        LOG.info("Executing operation getDomainSourcesByContent");
        System.out.println(contents);
        try {
            java.util.List<eu.comvantage.domainconfiguration.DomainSourceDetail> _return = new java.util.ArrayList<eu.comvantage.domainconfiguration.DomainSourceDetail>();
            eu.comvantage.domainconfiguration.DomainSourceDetail _returnVal1 = new eu.comvantage.domainconfiguration.DomainSourceDetail();
            java.util.List<java.lang.String> _returnVal1Content = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnVal1ContentVal1 = "_returnVal1ContentVal-1295947370";
            _returnVal1Content.add(_returnVal1ContentVal1);
            _returnVal1.getContent().addAll(_returnVal1Content);
            _returnVal1.setId(Long.valueOf(-2710325411291130877l));
            _returnVal1.setName("Name309191204");
            _returnVal1.setPassword("Password939105592");
            _returnVal1.setQueryEndpointURL("QueryEndpointURL685111765");
            _returnVal1.setType("Type-1354614140");
            _returnVal1.setUpdateEndpointURL("UpdateEndpointURL1879477781");
            _returnVal1.setUsername("Username1621078058");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.comvantage.domainconfiguration.DomainConfigurationServiceImpl#deleteDomainSource(eu.comvantage.domainconfiguration.DomainSourceDetail  source )*
     */
    public void deleteDomainSource(eu.comvantage.domainconfiguration.DomainSourceDetail source) { 
        LOG.info("Executing operation deleteDomainSource");
        System.out.println(source);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
